context: kadevakscluster

releases:
  - name: kick-prometheus
    namespace: prometheus
    chart: stable/prometheus
    version: ~7.4.6
    values:
      - rbac:
          create: false
      - alertmanager:
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi
      - kubeStateMetrics:
          resources:
            limits:
              cpu: 600m
              memory: 32Mi
            requests:
              cpu: 600m
              memory: 32Mi
      - nodeExporter:
          resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 30Mi
      - server:
          persistentVolume:
            enabled: true
            size: 24Gi
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
      - extraScrapeConfigs: |
          - job_name: bastion
            static_configs:
            - targets:
              - 10.12.0.5:9100
          - job_name: orchestrator
            static_configs:
            - targets:
              - 10.12.0.6:9100
          - job_name: nifidatahub1
            static_configs:
            - targets:
              - 10.12.0.7:9100
          - job_name: nifidatahub2
            static_configs:
            - targets:
              - 10.12.0.8:9100
          - job_name: swarmmaster
            static_configs:
            - targets:
              - 10.12.0.69:9100
          - job_name: swarmnodes
            static_configs:
            - targets:
              - 10.12.0.68:9100
              - 10.12.0.70:9100

      - pushgateway:
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi

  - name: kick-grafana
    namespace: prometheus
    chart: stable/grafana
    version: ~1.18.0
    values:
      - rbac:
          create: false
      - plugins:
          - grafana-clock-panel
          - grafana-piechart-panel
      - ingress:
          enabled: false
      - resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - persistence:
          enabled: true
          size: 16Gi
          accessModes:
            - ReadWriteOnce
          storageClassName: default
          annotations: {}
          subPath: ""
          existingClaim:
      - adminPassword: 'WkgKhJS3MkXGzmhrUP54IyNvkxDAWE9MQdjt53sR'
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://kick-prometheus-server.prometheus.svc.cluster.local
              access: proxy
              isDefault: true
