context: kadevakscluster

releases:
  - name: kick-prometheus
    namespace: prometheus
    chart: stable/prometheus
    version: ~7.4.5
    values:
      - prometheus/values.yaml

  - name: kick-grafana
    namespace: prometheus
    chart: stable/grafana
    version: ~1.18.0
    values:
      - ingress:
          enabled: false
          annotations:
            kubernetes.io/ingress.class: nginx
          path: /grafana/
          hosts: 10.12.0.102
      - resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
            
